### ISSUE TITLE
All checks were OK, but it still says 'This update was requested to be removed'

### ISSUE THREAD

**Issue by QiaoJianCheng** [JetBrains/intellij-plugin-verifier#13]
All checks were OK, but it still says 'This update was requested to be removed', why?

**Comment by QiaoJianCheng** [comment]
<img width="730" alt="WX20190625-144737@2x" src="https://user-images.githubusercontent.com/17694902/60075713-85d8b980-9758-11e9-9541-232ed93fe23e.png">
<img width="597" alt="WX20190625-144749@2x" src="https://user-images.githubusercontent.com/17694902/60075715-86715000-9758-11e9-8b53-3d1a2731168f.png">

**Comment by QiaoJianCheng** [comment]
And I didnt find my plugin in  marketplace.

**Comment by satamas** [comment]
This message is not related with verifier, it's shown when user have requested update removal. If you didn't requested removal it's a bug in plugin repository, it should be submitted to this [youtrack project](https://youtrack.jetbrains.com/issues/MP)

> And I didnt find my plugin in 
To become available in marketplace, your plugin should pass [approval process](https://plugins.jetbrains.com/legal/approval-guidelines)

**Comment by satamas** [comment]
And I've found bug in our repository, we've messed up with messages and showing message about removal instead of "This update is being reviewed by JetBrains, please expect it to be approved in two days after upload". 
Thanks for report, will fix it soon!

**Comment by QiaoJianCheng** [comment]
> And I've found bug in our repository, we've messed up with messages and showing message about removal instead of "This update is being reviewed by JetBrains, please expect it to be approved in two days after upload".
> Thanks for report, will fix it soon!

No wonder! I got it!
