### ISSUE TITLE
Deprecated method CodeStyleSettingsProvider.createSettingsPage() called by JetBrains class

### ISSUE THREAD

**Issue by xylo** [JetBrains/intellij-plugin-verifier#19]
The plugin verifier told me that I use the deprecated method `CodeStyleSettingsProvider.createSettingsPage()`.

However, my plugin is actually not calling this method directly.  Instead it calls `CodeStyleSettingsProvider.createConfigurable(...)` as suggested in the deprecation description, but `createConfigurable` calls `createSettingsPage` internally, and therefore the plugin verifier complains about it.

IMO either the plugin verifier should not complain about internally called deprecated methods or those methods should probably also be marked as deprecated.

**Comment by serejke** [comment]
Hello, @xylo.
As far as I see verification result for Custom Postfix Templates [2.10.8.193](https://plugins.jetbrains.com/plugin/9862-custom-postfix-templates/update/71100) says:
`Deprecated method CodeStyleSettingsProvider.createSettingsPage() is overridden in class CptCodeStyleSettingsProvider`

It is not about calling the `createSettingsPage` but overriding it, which is not-recommended for deprecated methods. Once the deprecated method gets removed, your inheritor's implementation won't be called, and it may lead to unexpected behavior changes.

I agree in that the verifier must not produce warnings for internally called deprecated methods, and it actually doesn't. May you show me the case where it happens?

**Comment by xylo** [comment]
Oh.  I haven't seen that.  Thanks!
