### ISSUE TITLE
version.txt or release not found

### ISSUE THREAD

**Issue by nek4life** [JetBrains/intellij-plugin-verifier#24]
It appears that the release file that the plugin is looking for is not in the specified location on Mac. I was able to fix the issue by manually moving the release file 

From `/Users/charliec/Library/Appl/Users/charliec/Library/Application\ Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.6668.13/IntelliJ\ IDEA\ 2020.1\ EAP.app/Contents/jbr/Contents/Home/release` 

To `/Users/charliec/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.6668.13/IntelliJ IDEA 2020.1 EAP.app/Contents/jbr/release`

Here is the original error 

`2020-03-31T08:33:46 [main] INFO  verification - Reading IDE /Users/charliec/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.6668.13/IntelliJ IDEA 2020.1 EAP.app/Contents
Exception in thread "main" java.lang.IllegalArgumentException: JDK version is not known: neither /Users/charliec/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.6668.13/IntelliJ IDEA 2020.1 EAP.app/Contents/jbr/release nor /Users/charliec/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.6668.13/IntelliJ IDEA 2020.1 EAP.app/Contents/jbr/version.txt are available`

Moving the file fixed the issue, however I'm wondering if this path could be added to the file lookup locations.

**Comment by izhangzhihao** [comment]
Same issue here, any fix or workaround?

**Comment by serejke** [comment]
Thanks for reporting the issue!
The `jbr/Contents/Home/release` path has been added to the known locations.

Please try to use the Plugin Verifier version 1.232 (now available in Bintray)
