### ISSUE TITLE
Verifier should exit with a non-zero status if the verification fails

### ISSUE THREAD

**Issue by PawelLipski** [JetBrains/intellij-plugin-verifier#27]
It'd be very convenient for scripted/CI use. Currently verifier jar exits with zero, even in case of major incompatibilities. This makes it necessary to parse the output to determine whether the verification passed or not, as in https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action/blob/master/entrypoint.sh#L243 or https://github.com/VirtusLab/git-machete-intellij-plugin/blob/master/scripts/verify-binary-compatibility#L50. This is pretty brittle since it relies on a specific intellij-plugin-verifier's output format.

**Comment by serejke** [comment]
There are many possible plugin verification verdicts. It is unclear what must be considered "successful" and "failed" results. If there are major incompatibilities, then it is clearly "failed" (except when we know about those reported problems, and they must be ignored). But what if at least 1 case of "internal API is used" is considered forbidden by a custom integration tool?
I believe, each integration must decide on its own.

The Plugin Verifier command-line always produces verification reports to a `-verification-reports-dir` (by default it is `<current working dir>/verification-<timestamp>`). I have documented the layout of files [here](https://github.com/JetBrains/intellij-plugin-verifier#results). Presence of corresponding files (e.g. presence of `compatibility-problems.txt`) may signal about the success/fail outcome.
