### ISSUE TITLE
Run configuration type not extracted if inheriting from SimpleConfigurationType

### ISSUE THREAD

**Issue by jansorg** [JetBrains/intellij-plugin-verifier#32]
[SimpleConfigurationType](https://github.com/JetBrains/intellij-community/blob/99c5e405e4839be546c4c68c064391ded4234642/platform/lang-api/src/com/intellij/execution/configurations/runConfigurationType.kt) is another commonly used base class for run configuration types.

It‘s used by the latest version of BashSupport Pro and the extractor didn’t find it. It only seems to check ConfigurationTypeBase, https://github.com/JetBrains/intellij-plugin-verifier/blob/master/intellij-feature-extractor/src/main/java/com/jetbrains/intellij/feature/extractor/extractor/RunConfigurationExtractor.kt

**Comment by serejke** [comment]
Replicated this ticket in YouTrack: https://youtrack.jetbrains.com/issue/MP-3239

**Comment by serejke** [comment]
Plugin Verifier project now uses YouTrack as the bug-tracking system. See #51.
