### ISSUE TITLE
TLDR Documentation

### ISSUE THREAD

**Issue by opticyclic** [JetBrains/intellij-plugin-verifier#33]
The README isn't easy to understand and needs to be updated to be clearer for people first coming to use the tool.

The second line of the README implies that it is targetting plugin developers:

> This tool is useful because plugins authors' often specify wide [since; until] compatibility range but compile a plugin against only a specific IDE from the range.

Since this is a plugin verifier it would make sense to put the `check-plugin` option first as this is most likely to be useful to plugin developers.

The current examples don't explain what the options are currently doing.
e.g.

> Check Kotlin plugin against IDEA Ultimate 162.2032.8, 163.1024 and 163.7277.
> 
> java -jar verifier-all.jar -runtime-dir /usr/lib/jvm/java-8-oracle check-plugin /tmp/Kotlin /tmp/IU-162.2032.8 /tmp/IU-163.1024 /tmp/IU-163.7277

Why is `runtime-dir` specified? Is this required or will it generally work without it?

This then raises other questions, such as "Will it use JAVA_HOME if I don't use that option?".  "Will it fail if I don't use that option?"

Examples that raise further questions aren't good examples.

The next point is the paths in this example `/tmp/Kotlin /tmp/IU-162.2032.8 /tmp/IU-163.1024 /tmp/IU-163.7277`.

How is the Kotlin plugin in `/tmp/Kotlin`?

Shouldn't you be passing in a relative path to the build directory of your plugin?

What the other directories `/tmp/IU-162.2032.8 /tmp/IU-163.1024 /tmp/IU-163.7277`?

Have you previously manually downloaded these and extracted them to this directory?

Does this mean the plugin require me to download every version of IDEA that I want to verify against?

Again, it is not clear and raises other questions.

e.g. If I have to download every version of IDEA that I want to test against, couldn't I just do that anyway and specify the path in my `build.gradle` in my plugin project?

Update the README to make the tool clear and easy to use for plugin developers.

**Comment by serejke** [comment]
Replicated this ticket in YouTrack: https://youtrack.jetbrains.com/issue/MP-3240

**Comment by serejke** [comment]
Plugin Verifier project now uses YouTrack as the bug-tracking system. See #51.
