### ISSUE TITLE
Specify Output Directory For Verification Results

### ISSUE THREAD

**Issue by opticyclic** [JetBrains/intellij-plugin-verifier#36]
I run the verifier like this:

    java -jar build/verifier-all.jar check-plugin build/distributions/antdebugger-1.4.0-SNAPSHOT.zip ~/opt/idea-IC-202.4357.23/

However, the output is always in the directory that I run the command e.g. `verification-2020-07-26 at 16.28.44`

I'd like to be able to specify the directory for the results.

e.g. specify "build/verifier/results" and end up with "build/verifier/results/verification-2020-07-26 at 16.28.44"

**Comment by serejke** [comment]
Now there is the [option](https://github.com/JetBrains/intellij-plugin-verifier#common-options) `-verification-reports-dir build/verifier/result`.
