### ISSUE TITLE
Specify Verification Date Format

### ISSUE THREAD

**Issue by opticyclic** [JetBrains/intellij-plugin-verifier#37]
The results currently output in directories like `verification-2020-07-26 at 16.28.44`.

I don't like the spaces and would rather it looked something like this `verification-2020-07-26_16-28-44`

It would be useful to add an option to specify the output directory format so I can customise it to whatever I want form the command line.

**Comment by serejke** [comment]
Replicated this ticket in YouTrack: https://youtrack.jetbrains.com/issue/MP-3242

**Comment by serejke** [comment]
Plugin Verifier project now uses YouTrack as the bug-tracking system. See #51.
