### ISSUE TITLE
Output All Results In HTML Report

### ISSUE THREAD

**Issue by opticyclic** [JetBrains/intellij-plugin-verifier#38]
The HTML report currently says:

> Compatible. 8 usages of deprecated API
> No problems.

However, it doesn't specify the details of the deprecated API.

I can only get that from the command line.

I'd rather look at the HTML in TeamCity to see the results than search through the logs for the raw output.

**Comment by serejke** [comment]
Replicated this ticket in YouTrack: https://youtrack.jetbrains.com/issue/MP-3243

**Comment by serejke** [comment]
Plugin Verifier project now uses YouTrack as the bug-tracking system. See #51.
