### ISSUE TITLE
plugin.xml is not verified

### ISSUE THREAD

**Issue by hsz** [JetBrains/intellij-plugin-verifier#7]
In my `plugin.xml` manifest I am referring to `lang.syntaxHighlighterFactory`. Its `key` property has been deprecated:

![image](https://user-images.githubusercontent.com/108333/43131817-408649aa-8f3a-11e8-841e-0976f5ae4762.png)

Unfortunatelly this issue was not reported by the Verifier.

**Comment by serejke** [comment]
Indeed, that makes sense.
Filed a corresponding task https://youtrack.jetbrains.com/issue/MP-1823.
Thank you!

**Comment by serejke** [comment]
Plugin Verifier project now uses YouTrack as the bug-tracking system. See #51.
