### ISSUE TITLE
Plugin verifier complains about 'icons' package

### ISSUE THREAD

**Issue by serge17** [JetBrains/intellij-plugin-verifier#9]
Verifier gives the following warning for `icons` package even though it is the suggested way of naming a package with the icons interface (http://www.jetbrains.org/intellij/sdk/docs/reference_guide/work_with_icons_and_images.html).
```
The plugin distribution contains IDE packages: icons. Bundling IDE classes is considered bad practice and may lead to sophisticated compatibility problems. Consider excluding IDE classes from the plugin distribution and reusing the IDE's classes. If your plugin depends on classes of an IDE bundled plugin, explicitly specify dependency on that plugin instead of bundling it.
```

![image](https://user-images.githubusercontent.com/18661283/54730096-7d1a8b00-4b4c-11e9-842a-b620ac7cbc7c.png)

**Comment by serejke** [comment]
Thanks for notifying!
Indeed, it used to be a bug that I've just fixed.
Where did you notice this warning? If it has come from the Plugin Repository, I'd like to re-run the verification to get rid of this false positive. Otherwise, if you run the verifier manually, please use version 1.208+.
Thanks!

**Comment by serejke** [comment]
I've found that you are probably was talking about [Contrast plugin 2.5.1](https://plugins.jetbrains.com/plugin/10335-contrast/update/59227).
I've re-run the verificaition for 2019.1 and now it reports total compatibility. 
Congrats!

**Comment by serge17** [comment]
@serejke Thanks!
